# Generated by Django 5.2.4 on 2025-07-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_fielddefinition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fielddefinition',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
